#ifndef S_TERMINALCOLOR_H
#define S_TERMINALCOLOR_H

//
// colors for a terminal
//

#define S_TERMINALCOLOR_RESET   "\x1B[0m"
#define S_TERMINALCOLOR_BLACK   "\x1B[0;30m"
#define S_TERMINALCOLOR_RED     "\x1B[0;31m"
#define S_TERMINALCOLOR_GREEN   "\x1B[0;32m"
#define S_TERMINALCOLOR_YELLOW  "\x1B[0;33m"
#define S_TERMINALCOLOR_BLUE    "\x1B[0;34m"
#define S_TERMINALCOLOR_MAGENTA "\x1B[0;35m"
#define S_TERMINALCOLOR_CYAN    "\x1B[0;36m"
#define S_TERMINALCOLOR_WHITE   "\x1B[0;37m"
#define S_TERMINALCOLOR_BOLD_BLACK   "\x1B[1;30m"
#define S_TERMINALCOLOR_BOLD_RED     "\x1B[1;31m"
#define S_TERMINALCOLOR_BOLD_GREEN   "\x1B[1;32m"
#define S_TERMINALCOLOR_BOLD_YELLOW  "\x1B[1;33m"
#define S_TERMINALCOLOR_BOLD_BLUE    "\x1B[1;34m"
#define S_TERMINALCOLOR_BOLD_MAGENTA "\x1B[1;35m"
#define S_TERMINALCOLOR_BOLD_CYAN    "\x1B[1;36m"
#define S_TERMINALCOLOR_BOLD_WHITE   "\x1B[1;37m"
#define S_TERMINALCOLOR_UNDERLINE_BLACK   "\x1B[4;30m"
#define S_TERMINALCOLOR_UNDERLINE_RED     "\x1B[4;31m"
#define S_TERMINALCOLOR_UNDERLINE_GREEN   "\x1B[4;32m"
#define S_TERMINALCOLOR_UNDERLINE_YELLOW  "\x1B[4;33m"
#define S_TERMINALCOLOR_UNDERLINE_BLUE    "\x1B[4;34m"
#define S_TERMINALCOLOR_UNDERLINE_MAGENTA "\x1B[4;35m"
#define S_TERMINALCOLOR_UNDERLINE_CYAN    "\x1B[4;36m"
#define S_TERMINALCOLOR_UNDERLINE_WHITE   "\x1B[4;37m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BLACK   "\x1B[0;90m"
#define S_TERMINALCOLOR_HIGHINTENSITY_RED     "\x1B[0;91m"
#define S_TERMINALCOLOR_HIGHINTENSITY_GREEN   "\x1B[0;92m"
#define S_TERMINALCOLOR_HIGHINTENSITY_YELLOW  "\x1B[0;93m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BLUE    "\x1B[0;94m"
#define S_TERMINALCOLOR_HIGHINTENSITY_MAGENTA "\x1B[0;95m"
#define S_TERMINALCOLOR_HIGHINTENSITY_CYAN    "\x1B[0;96m"
#define S_TERMINALCOLOR_HIGHINTENSITY_WHITE   "\x1B[0;97m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_BLACK   "\x1B[1;90m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_RED     "\x1B[1;91m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_GREEN   "\x1B[1;92m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_YELLOW  "\x1B[1;93m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_BLUE    "\x1B[1;94m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_MAGENTA "\x1B[1;95m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_CYAN    "\x1B[1;96m"
#define S_TERMINALCOLOR_HIGHINTENSITY_BOLD_WHITE   "\x1B[1;97m"
#define S_TERMINALCOLOR_BACKGROUND_BLACK   "\x1B[40m"
#define S_TERMINALCOLOR_BACKGROUND_RED     "\x1B[41m"
#define S_TERMINALCOLOR_BACKGROUND_GREEN   "\x1B[42m"
#define S_TERMINALCOLOR_BACKGROUND_YELLOW  "\x1B[43m"
#define S_TERMINALCOLOR_BACKGROUND_BLUE    "\x1B[44m"
#define S_TERMINALCOLOR_BACKGROUND_MAGENTA "\x1B[45m"
#define S_TERMINALCOLOR_BACKGROUND_CYAN    "\x1B[46m"
#define S_TERMINALCOLOR_BACKGROUND_WHITE   "\x1B[47m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_BLACK   "\x1B[0;100m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_RED     "\x1B[0;101m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_GREEN   "\x1B[0;102m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_YELLOW  "\x1B[0;103m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_BLUE    "\x1B[0;104m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_MAGENTA "\x1B[0;105m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_CYAN    "\x1B[0;106m"
#define S_TERMINALCOLOR_BACKGROUND_HIGHINTENSITY_WHITE   "\x1B[0;107m"


// setup the terminal to handle color codes
// just for windows...
void s_terminalcolor_start();

// stop the terminal from using color codes
// just for windows...
void s_terminalcolor_stop();

#endif //S_TERMINALCOLOR_H
